-- -----------------------------------------------------
-- Table carreras_cuatrimestres
-- -----------------------------------------------------
insert into materias values(1,'Calculo diferencial');
insert into materias values(2,'Base de Datos para Aplicaciones');
insert into materias values(3,'Aplicaciones Web');
insert into materias values(4,'Sistemas Operativos');
insert into materias values(5,'Ingles I');
insert into materias values(6,'Álgebra lineal');
insert into materias values(7,'Desarrollo de habilidades de pensamiento lógico');
insert into materias values(8,'Fundamentos de TI');
insert into materias values(9,'Fundamentos de redes');
insert into materias values(10,'Metodología de la programación');
insert into materias values(11,'Expresion oral y escrita I');
insert into materias values(12,'Formación sociocultural I');
insert into materias values(13,'Funciones matemáticas');
insert into materias values(14,'Metodologías y modelado de desarrollo de software');
insert into materias values(15,'Interconexión de redes');
insert into materias values(16,'Programación orientada a objetos');
insert into materias values(17,'Base de Datos para Aplicaciones');
insert into materias values(18,'Introducción al diseño digital');
insert into materias values(19,'Base de datos');
insert into materias values(20,'Probabilidad y estadística');
insert into materias values(21,'Estándares y métricas para el desarrollo de software');
insert into materias values(22,'Principios para IoT');
insert into materias values(23,'Diseño de apps');
insert into materias values(24,'Estructura de datos aplicadas');
insert into materias values(25,'Aplicaciones web orientadas a servicios');
insert into materias values(26,'Evaluación y mejora para el desarrollo de software');
insert into materias values(27,'Aplicaciones de IoT');
insert into materias values(28,'Desarrollo móvil multiplataforma');
insert into materias values(29,'Aplicaciones web para 14.0');
insert into materias values(30,'Introducción a Big Data');
insert into materias values(31,'Administración de redes de datos');
insert into materias values(32,'Base de Datos para Aplicaciones');
insert into materias values(33,'Programación de redes');
insert into materias values(34,'Bases de datos para cómputo en la nube');
insert into materias values(35,'Infraestructura de redes de datos');
insert into materias values(36,'Electrónica para IdC');
insert into materias values(37,'Conexiones de redes WAN');
insert into materias values(38,'Administración de servidores I');
insert into materias values(39,'Administración de servidores II');
insert into materias values(40,'Infomática para diseño de moda');
insert into materias values(41,'Creatividad del diseño');
insert into materias values(42,'Técnicas de ilustración');
insert into materias values(43,'Patronaje industrial para dama');
insert into materias values(44,'Métodos de confección I');
insert into materias values(45,'Historia del arte y la moda');
insert into materias values(46,'Fundamentos textiles I');
insert into materias values(47,'Teoría del color');
insert into materias values(48,'Ilustración de modas por computadora I');
insert into materias values(49,'Patronaje industrial para caballero y niño');
insert into materias values(50,'Matemáticas');
insert into materias values(51,'Ilustración de modas por computadora II');
insert into materias values(52,'Métodos de confección II');
insert into materias values(53,'Sistemas de graduación industrial');
insert into materias values(54,'Fundamentos textiles II');
insert into materias values(55,'Metodología de la investigación');
insert into materias values(56,'Estadística');
insert into materias values(57,'Costos de manufactura');
insert into materias values(58,'Planeación de la producción');
insert into materias values(59,'Mercadotecnia de la moda');
insert into materias values(60,'Patronaje por computadora');
insert into materias values(61,'Calidad en la industria del vestido');
insert into materias values(62,'Sistemas de confección industrial');
insert into materias values(63,'Procesos de manufactura');
insert into materias values(64,'Graduación por computadora');
insert into materias values(65,'Fundamentos del diseño');
insert into materias values(66,'Representación visual');
insert into materias values(67,'Fundamentos de la comunicación gráfica');
insert into materias values(68,'Informática aplicada al diseño');
insert into materias values(69,'Geometría');
insert into materias values(70,'Elementos del lenguaje visual');
insert into materias values(71,'Ilustración I');
insert into materias values(72,'Modelado manual');
insert into materias values(73,'Representación geométrica');
insert into materias values(74,'Levantamiento de objetos y espacios');
insert into materias values(75,'Proceso administrativo');
insert into materias values(76,'Costos');
insert into materias values(77,'Ilustración II');
insert into materias values(78,'Fotografía digital');
insert into materias values(79,'Mercadotecnia');
insert into materias values(80,'Software CAD');
insert into materias values(81,'Física');
insert into materias values(82,'Animación 2D');
insert into materias values(83,'Guionismo y storyboard');
insert into materias values(84,'Prototipos');
insert into materias values(85,'Proceso de diseño');
insert into materias values(86,'Diseño editorial digital');
insert into materias values(87,'Animación en 3D');
insert into materias values(88,'Edición de audio y video');
insert into materias values(89,'Imagen digital animada');
insert into materias values(90,'Expresión Oral y Escrita II');
insert into materias values(91,'Inglés V');
insert into materias values(92,'Formación sociocultural IV');
insert into materias values(93,'Formación sociocultural III');
insert into materias values(94,'Inglés III');